name: Build Docker Container
run-name: ${{ github.actor }} is building Docker container
on:
    push:
        branches:
            - main
jobs:
        build:
          runs-on: ubuntu-latest
          steps:
              - name: login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registery: ghcr.io
                    username: ${{ secrets.GHCR_USERNAME }}
                    password: ${{ secrets.GHCR_TOKEN }}
              - uses: actions/checkout@v2
              - name: create image from repository
                run: docker build -t ghcr.io/${{ github.actor }}/vaultwarden_backup .
              - name: push image to GitHub Container Registry
                run: docker push ghcr.io/${{ github.actor }}/vaultwarden_backup:latest

